apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tamyona/api:1.0.0
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DBHOST
              value: "mysql.svc.cluster.local"    # provide service of mysql
            - name: DBPORT
              value: "3306"
            - name: DB
              value: "kaizen"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
          # startupProbe:
          #   httpGet:
          #     path: /health
          #     port: 3001
          #   failureThreshold: 30
          #   periodSeconds: 5