apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: LoadBalancer  # Change to ClusterIP if only accessible internally
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001