apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # base64 encoded 'password'
  mysql-user: dXNlcm5hbWU=          # base64 encoded 'username'
  mysql-password: c2VjdXJlcGFzcw==  # base64 encoded 'securepass'