- name: Install Kubernetes Dependencies 
  ansible.builtin.apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /tmp/kubernetes-apt-keyring.gpg
    mode: "0644"

- name: Convert Kubernetes GPG key to dearmored format
  ansible.builtin.command:
    cmd: gpg --dearmor --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg  # Prevents redundant execution

- name: Set permissions for Kubernetes GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: "0644"

- name: Clean up temporary key file
  ansible.builtin.file:
    path: /tmp/kubernetes-apt-keyring.gpg
    state: absent

- name: Add the repository to Apt sources using tee
  ansible.builtin.shell:
    cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Add Kubernetes APT repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    owner: root
    group: root
    mode: "0644"

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: yes