apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  externalIPs: 
    - 52.14.215.144
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000